version: "3.9"
services:
db:
image: mariadb:10.11
restart: unless-stopped
environment:
MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
MYSQL_DATABASE: ${DB_NAME:-app}
MYSQL_USER: ${DB_USER:-app}
MYSQL_PASSWORD: ${DB_PASSWORD:-app}
ports:
- "3306:3306"
volumes:
- db_data:/var/lib/mysql
healthcheck:
test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "$$MYSQL_USER", "--password=$$MYSQL_PASSWORD"]
interval: 10s
timeout: 5s
retries: 10


api:
  build: ./api
  restart: unless-stopped
  env_file: ./api/.env
  ports:
    - "8080:8080"
  depends_on:
  db:
  condition: service_healthy


  volumes:
  db_data: {}