// src/integrations/metahub/rtk/tags.ts

// RTK Query createApi -> tagTypes: readonly string[] bekler.
// Bu listeyi 'as const' ile sabitliyoruz.
export const metahubTags = [
  "Auth","User","Users",
  "Functions",
  "Profile",
  "Products","Product",
  "Categories",
  "Faqs",
  "Reviews",
  "Options","Option","OptionValue","OptionGroups","OptionGroup",
  "Stock","StockItems","StockItem",
  "Order","Orders","OrderItem","OrderItems",
  "CartItem","CartItems",
  "Coupon","Coupons",
  "BlogPost","BlogPosts",
  "SupportTicket","SupportTickets",
  "TicketReply","TicketReplies",
  "MenuItem","MenuItems",
  "FooterSection","FooterSections",
  "CustomPage","CustomPages",
  "Popup","Popups",
  "EmailTemplate","EmailTemplates",
  "Variant","Variants",
  "WalletTransactions",
  "PaymentRequests",
  "SiteSettings",
  "PaymentProvider","PaymentProviders",
  "PaymentSession","PaymentSessions",
  "StorageUpload",
  "Notification","Notifications",
  "Activity","Activities",
  "Audit","Audits",
  "Telemetry","Telemetries",
  "Health",
  "AuditLogs",
  "ConfigHistory",
  "Subscriptions","Subscription",
  "Promotion",
  "Disputes","Dispute",
  "Settlements","Settlement",
  "Webhooks","Webhook",
  "Flags","Flag",
  "Payments","Payment",
  "Permissions","Permission",
  "Invoices","Invoice",
  "UserRoles","UserRole",
  "TopbarSettings","TopbarSetting",
  "WalletDepositRequests","WalletDepositRequest",
  "RPC","Rpc",
  "CmsPage","CmsPages",
  "CmsBlocks","CmsBlock","CmsMenu","CmsMenus",
  "MediaAssets","MediaAsset",
  "MediaFolders","MediaFolder",
  "Redirects","Redirect",
] as const;

export type MetahubTag = typeof metahubTags[number];
