-- 69_blog_posts_seed.sql
-- Initial blog posts data (idempotent via ON DUPLICATE KEY UPDATE)

INSERT INTO `blog_posts`
(`id`, `title`, `slug`, `excerpt`, `content`, `featured_image`, `author`, `meta_title`, `meta_description`, `is_published`, `published_at`, `created_at`, `updated_at`)
VALUES
('42b8c68c-9589-40a3-82a9-401fd23406d1', 'Sosyal Medya Pazarlamasında 2024 Trendleri', 'sosyal-medya-pazarlamasinda-2024-trendleri', 'Sosyal medya pazarlamasında öne çıkan son trendler ve bu trendleri işinizde nasıl kullanabileceğiniz.', '<h2>Sosyal Medya Pazarlamasının Geleceği</h2><p>2024 yılında sosyal medya pazarlaması, markaların müşterileriyle etkileşime geçmesinin en önemli yollarından biri olmaya devam ediyor.</p><h3>Video İçerik Hakimiyeti</h3><p>Kısa video içerikler, sosyal medya platformlarında en çok tüketilen içerik türü haline geldi. TikTok, Instagram Reels ve YouTube Shorts gibi platformlar, markaların geniş kitlelere ulaşmasını sağlıyor.</p><h3>Influencer İşbirlikleri</h3><p>Mikro ve makro influencer\'larla yapılan işbirlikleri, marka bilinirliğini artırmak ve hedef kitleye ulaşmak için etkili bir strateji olmaya devam ediyor.</p>', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=600&fit=crop', 'Admin', NULL, NULL, 1, '2025-10-12 11:34:11', '2025-10-12 11:34:11', '2025-10-12 11:34:11'),
('56e4088e-0195-46ae-b016-aa4d73c70379', 'En İyi Oyun Lisansları 2025s', 'en-iyi-oyun-lisanslari-2025s', '2025 yılının en popüler oyun lisansları ve önerileri. Hangi oyunları tercih etmelisiniz?', '<h2>2025 Yılının En Çok Tercih Edilen Oyunları</h2><p>Bu yıl oyun dünyasında birçok yenilik ve heyecan verici içerik bulunuyor. İşte en çok tercih edilen oyunlar:</p><h3>Aksiyon Oyunları</h3><p>Bu kategoride en popüler oyunlar arasında son çıkan AAA yapımlar yer alıyor.</p><h3>Strateji Oyunları</h3><p>Düşünmeyi seven oyuncular için harika seçenekler mevcut.</p><h3>Multiplayer Deneyimleri</h3><p>Arkadaşlarınızla oynayabileceğiniz en iyi co-op oyunlar.</p>', 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=600&fit=crop', 'Ahmet Yılmaz', NULL, NULL, 1, '2025-10-06 22:06:38', '2025-10-06 22:06:38', '2025-10-06 22:30:37'),
('6af13cbe-906c-4ad3-af83-4f2dcb5d5359', 'Dijital Ürün Satışında Başarı İpuçları', 'dijital-urun-satisinda-basari-ipuclari', 'Dijital ürün satışında başarılı olmak için bilmeniz gereken temel stratejiler ve ipuçları.', '<h2>Dijital Ürün Satışının Temelleri</h2><p>Dijital ürün satışı, günümüzün en karlı iş modellerinden biri haline geldi. Bu yazıda, dijital ürün satışında başarılı olmanız için bilmeniz gereken temel stratejileri paylaşacağız.</p><h3>Hedef Kitlenizi Tanıyın</h3><p>Başarılı bir dijital ürün satışı için öncelikle hedef kitlenizi iyi tanımalısınız. Müşterilerinizin ihtiyaçlarını, beklentilerini ve sorunlarını anlamak, size doğru ürünleri sunma konusunda yardımcı olacaktır.</p><h3>Kaliteli Hizmet Sunun</h3><p>Dijital ürün satışında müşteri memnuniyeti her şeyden önemlidir. Hızlı teslimat, güvenilir ödeme sistemleri ve 7/24 destek hizmeti sunarak müşterilerinizin güvenini kazanabilirsiniz.</p>', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop', 'Admin', NULL, NULL, 1, '2025-10-12 11:34:11', '2025-10-12 11:34:11', '2025-10-12 11:34:11'),
('c33488f7-12b7-4a58-b67c-7903589da484', 'Oyun Kredileri ve E-Pin Kullanım Rehberi', 'oyun-kredileri-ve-e-pin-kullanim-rehberi', 'Oyun kredileri ve e-pin\'leri güvenli bir şekilde nasıl satın alır ve kullanırsınız? Detaylı rehberimizle öğrenin.', '<h2>E-Pin ve Oyun Kredileri Nedir?</h2><p>E-pin\'ler ve oyun kredileri, dijital oyunlar ve platformlar için kullanılan ön ödemeli kodlardır. Bu rehberde, e-pin\'leri güvenli bir şekilde nasıl satın alacağınızı ve kullanacağınızı öğreneceksiniz.</p><h3>Güvenli Satın Alma İpuçları</h3><p>E-pin satın alırken mutlaka güvenilir platformları tercih edin. Satıcının yorumlarını kontrol edin ve güvenli ödeme yöntemlerini kullanın.</p><h3>Kullanım Adımları</h3><p>E-pin\'inizi aldıktan sonra, ilgili platformun kod girme bölümüne gidin ve kodunuzu girin. Kredi veya içerik hesabınıza anında yüklenecektir.</p>', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=600&fit=crop', 'Admin', NULL, NULL, 1, '2025-10-12 11:34:11', '2025-10-12 11:34:11', '2025-10-12 11:34:11'),
('c71dd534-d010-45a0-9da7-1ce4aff90dbb', 'Microsoft Office Lisansı Nasıl Seçilir?', 'microsoft-office-lisansi-nasil-secilirs', 'İşletmeniz veya kişisel kullanımınız için en uygun Office lisansını seçme rehberi.', '<h2>Office Lisans Türleri</h2><p>Microsoft Office birçok farklı lisans seçeneği sunuyor. Hangisinin sizin için uygun olduğunu belirleyelim.</p><h3>Microsoft 365 Personal</h3><p>Bireysel kullanıcılar için ideal olan bu paket, 1 PC veya Mac üzerinde kullanılabilir.</p><h3>Microsoft 365 Family</h3><p>Aile üyeleriyle paylaşabileceğiniz, 6 kişiye kadar lisans sunan ekonomik paket.</p><h3>Office Home &amp; Business</h3><p>Küçük işletmeler için tek seferlik satın alma seçeneği ile maliyet avantajı.</p><h3>Karar Verirken Nelere Dikkat Edilmeli?</h3><p>İhtiyacınız olan programlar, cihaz sayısı ve bütçenizi göz önünde bulundurarak karar verin.</p>', NULL, 'Ayşa', NULL, NULL, 1, '2025-10-06 22:06:38', '2025-10-06 22:06:38', '2025-10-09 09:29:03'),
('d8db9721-6067-40be-8122-5605dba2bc7f', 'Spotify Premium vs YouTube Music', 'spotify-premium-vs-youtube-music', 'İki popüler müzik platformunu karşılaştırdık. Hangisi sizin için daha uygun?', '<h2>Müzik Platformları Karşılaştırması</h2><p>Günümüzde müzik dinleme alışkanlıklarımız tamamen değişti. Peki hangi platform sizin için daha uygun?</p><h3>Spotify Premium Avantajları</h3><ul><li>Geniş müzik kütüphanesi</li><li>Kişiselleştirilmiş çalma listeleri</li><li>Yüksek ses kalitesi</li><li>Offline dinleme</li></ul><h3>YouTube Music Avantajları</h3><ul><li>YouTube videolarına erişim</li><li>Geniş içerik yelpazesi</li><li>Remix ve cover versiyonlar</li><li>YouTube Premium ile entegrasyon</li></ul><h3>Fiyat Karşılaştırması</h3><p>Her iki platform da rekabetçi fiyatlar sunuyor. Öğrenci ve aile paketleriyle maliyet avantajı sağlayabilirsiniz.</p>', 'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=800&h=600&fit=crop', 'Mehmet Kaya', NULL, NULL, 1, '2025-10-06 22:06:38', '2025-10-06 22:06:38', '2025-10-06 22:06:38'),
('e1159124-e6f4-4569-8df8-ed762e7b4b9e', 'Dijital Ürünlerde Güvenlik İpuçları', 'dijital-urunlerde-guvenlik-ipuclari', 'Dijital ürünleri satın alırken güvenliğinizi sağlamak için bilmeniz gereken önemli ipuçları.', '<h2>Güvenli Alışverişin Temel Kuralları</h2><p>Dijital ürünler satın alırken dikkat etmeniz gereken en önemli noktalar nelerdir? Bu yazıda sizin için önemli güvenlik ipuçlarını derledik.</p><h3>1. Güvenilir Platformları Tercih Edin</h3><p>Her zaman SSL sertifikası olan ve güvenli ödeme yöntemlerine sahip platformları kullanın.</p><h3>2. Şifre Güvenliği</h3><p>Hesaplarınız için güçlü ve benzersiz şifreler kullanın. İki faktörlü kimlik doğrulamayı aktif edin.</p><h3>3. Ödeme Bilgilerinizi Koruyun</h3><p>Kredi kartı bilgilerinizi sadece güvenilir platformlarda paylaşın ve düzenli olarak hesap hareketlerinizi kontrol edin.</p>', 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=600&fit=crop', 'Dijimin Ekibi', NULL, NULL, 1, '2025-10-06 22:06:38', '2025-10-06 22:06:38', '2025-10-06 22:06:38')
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `slug` = VALUES(`slug`),
  `excerpt` = VALUES(`excerpt`),
  `content` = VALUES(`content`),
  `featured_image` = VALUES(`featured_image`),
  `author` = VALUES(`author`),
  `meta_title` = VALUES(`meta_title`),
  `meta_description` = VALUES(`meta_description`),
  `is_published` = VALUES(`is_published`),
  `published_at` = VALUES(`published_at`),
  `updated_at` = VALUES(`updated_at`);
